spring.application.name=MovieBookingApplication


# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT CONFIG (Base64 Encoded Secret)
jwt.secretkey = ZHVtbXlTZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkw
jwt.expiration = 3600000
